/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe_management_system;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Azizul Hakim'PC
 */
public class Dashboard extends javax.swing.JFrame {

    String email;

    public Dashboard(String username) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        email = username;
        if (!email.equals("admin@gmail.com")) {
            btnmanage.setVisible(false);
            btneditproduct.setVisible(false);
            btnproduct.setVisible(false);
            btnverify.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout = new javax.swing.JButton();
        placeOrder = new javax.swing.JButton();
        bill = new javax.swing.JButton();
        pass = new javax.swing.JButton();
        ques = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        btnmanage = new javax.swing.JButton();
        btnproduct = new javax.swing.JButton();
        btneditproduct = new javax.swing.JButton();
        btnverify = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.setText("LogOut");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        placeOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        placeOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        placeOrder.setText("Place Order");
        placeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderActionPerformed(evt);
            }
        });
        getContentPane().add(placeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        bill.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Bills & Order Placed Details.png"))); // NOI18N
        bill.setText("View Bill & Order Placed Details");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        getContentPane().add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        pass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Password.png"))); // NOI18N
        pass.setText("Change Password");
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        ques.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Security Question.png"))); // NOI18N
        ques.setText("Change Security Question");
        ques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quesActionPerformed(evt);
            }
        });
        getContentPane().add(ques, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, -1, -1));

        exit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 70, -1, -1));

        btnmanage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnmanage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        btnmanage.setText("Manage Category");
        btnmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageActionPerformed(evt);
            }
        });
        getContentPane().add(btnmanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 650, -1, -1));

        btnproduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        btnproduct.setText("New Product");
        btnproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductActionPerformed(evt);
            }
        });
        getContentPane().add(btnproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 650, -1, -1));

        btneditproduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btneditproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        btneditproduct.setText("View,edit & Delete Product");
        btneditproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditproductActionPerformed(evt);
            }
        });
        getContentPane().add(btneditproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 650, -1, -1));

        btnverify.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnverify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
        btnverify.setText("Verify Users");
        btnverify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnverify, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 650, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Are you Really Want to Log Out?", "Select", JOptionPane.YES_NO_OPTION);
        if (s == 0) {
            this.setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Are you Really Want to Exit?", "Select", JOptionPane.YES_NO_OPTION);
        if (s == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed

        new ChangePassword(email).setVisible(true);
    }//GEN-LAST:event_passActionPerformed

    private void btnmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageActionPerformed

        new ManageCategory().setVisible(true);
    }//GEN-LAST:event_btnmanageActionPerformed

    private void btnproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductActionPerformed
        new NewProduct().setVisible(true);
    }//GEN-LAST:event_btnproductActionPerformed

    private void btneditproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditproductActionPerformed
        this.setVisible(false);
        new View_Edit_DeleteProduct(email).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btneditproductActionPerformed

    private void btnverifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyActionPerformed
        this.setVisible(false);
        new VerifyUsers(email).setVisible(true);
    }//GEN-LAST:event_btnverifyActionPerformed

    private void placeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderActionPerformed
        this.setVisible(false);
        new PlaceOrder(email).setVisible(true);
    }//GEN-LAST:event_placeOrderActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        this.setVisible(false);
        new View_Bill_Order_Details(email).setVisible(true);
    }//GEN-LAST:event_billActionPerformed

    private void quesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quesActionPerformed
        new Change_Question_Answer(email).setVisible(true);
    }//GEN-LAST:event_quesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bill;
    private javax.swing.JButton btneditproduct;
    private javax.swing.JButton btnmanage;
    private javax.swing.JButton btnproduct;
    private javax.swing.JButton btnverify;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton pass;
    private javax.swing.JButton placeOrder;
    private javax.swing.JButton ques;
    // End of variables declaration//GEN-END:variables
}
