/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe_management_system;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Azizul Hakim'PC
 */
public class PlaceOrder extends javax.swing.JFrame {

    String Usermail;
    int price, grandtotal;
    String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    String mobilePattern = "^[0-9]*$";

    /**
     * Creates new form PlaceOrder
     *
     * @param userEmail
     */
    public PlaceOrder(String userEmail) {
        Usermail = userEmail;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        txtproName.setEditable(false);
        txtproPrice.setEditable(false);
        txtProTotal.setEditable(false);
        spin.setEnabled(false);
        btnAddCart.setEnabled(false);
        btnBill.setEnabled(false);

    }

    public void clear() {
        txtproName.setText("");
        txtproPrice.setText("");
        txtProTotal.setText("");
        spin.setEnabled(false);
        btnAddCart.setEnabled(false);
    }

    public void ValidateFields() {
        String name = cusName.getText();
        String mobile = cusMobile.getText();
        String email = cusEmail.getText();
        if (!email.equals("") && mobile.matches(mobilePattern) && mobile.length() == 11 && email.matches(emailPattern) & grandtotal > 0) {
            btnBill.setEnabled(true);
        } else {
            btnBill.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Bill = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cusName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cusMobile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cusEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtproName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        spin = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtproPrice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtProTotal = new javax.swing.JTextField();
        btnAddCart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        btnBill = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        grandTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        jLabel1.setText("Place Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1319, 11, 31, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bill ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 80, -1, -1));

        Bill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bill.setForeground(new java.awt.Color(255, 255, 255));
        Bill.setText("--");
        getContentPane().add(Bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer Details:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        cusName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cusName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cusNameKeyReleased(evt);
            }
        });
        getContentPane().add(cusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 236, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        cusMobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cusMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cusMobileKeyReleased(evt);
            }
        });
        getContentPane().add(cusMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 236, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        cusEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cusEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cusEmailKeyReleased(evt);
            }
        });
        getContentPane().add(cusEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 236, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Category");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 60, 20));

        combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMouseClicked(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 240, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 50, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 240, -1));

        table1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        table1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                table1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 240, 430));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, -1, -1));

        txtproName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtproName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtproName, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 220, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quantity");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, -1, -1));

        spin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinStateChanged(evt);
            }
        });
        getContentPane().add(spin, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 220, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 80, -1, -1));

        txtproPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtproPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 230, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 140, -1, -1));

        txtProTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtProTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 160, 230, -1));

        btnAddCart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        btnAddCart.setText("Add to Cart");
        btnAddCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 200, 140, -1));

        table2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 520, 380));

        btnBill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        btnBill.setText("Generate Bill & Print");
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 660, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Grand Total:  BDT.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 670, -1, -1));

        grandTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        grandTotal.setForeground(new java.awt.Color(255, 255, 255));
        grandTotal.setText("00");
        getContentPane().add(grandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 670, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("*Click on row to");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 430, -1, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText(" remove the product");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 450, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtproNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Dashboard(Usermail).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        String q1 = "select max(id) from bill";
        conn c = new conn();
        int id = 1;
        try {
            ResultSet rs = c.s.executeQuery(q1);
            while (rs.next()) {
                id = rs.getInt(1);
                id = id + 1;
                Bill.setText(String.valueOf(id));
            }
        } catch (Exception e) {
        }
        String q2 = "select * from category";
        try {
            ResultSet rs1 = c.s.executeQuery(q2);
            while (rs1.next()) {
                combo.addItem(rs1.getString("name"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formComponentShown

    private void comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseClicked

    }//GEN-LAST:event_comboMouseClicked

    private void table1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_table1ComponentShown

    }//GEN-LAST:event_table1ComponentShown

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        String category = (String) combo.getSelectedItem();
        String q3 = "select * from productTable where category='" + category + "'";
        String proName = null;
        conn c = new conn();
        DefaultTableModel tdf = (DefaultTableModel) table1.getModel();
        tdf.setRowCount(0);
        try {
            ResultSet rs2 = c.s.executeQuery(q3);
            while (rs2.next()) {

                proName = rs2.getString("name");
                String tb[] = {proName};
                tdf.addRow(tb);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_comboActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        DefaultTableModel tdf = (DefaultTableModel) table1.getModel();
        spin.setEnabled(true);
        spin.setValue(1);
        String name = (String) tdf.getValueAt(table1.getSelectedRow(), 0);
        String q3 = "select * from productTable where name='" + name + "'";
        conn c = new conn();
        int quantity = 0, total = 0;
        try {
            ResultSet rs2 = c.s.executeQuery(q3);
            while (rs2.next()) {
                price = Integer.parseInt(rs2.getString("price"));
                quantity = (int) spin.getValue();
                total = price * quantity;
            }
            txtproName.setText(name);
            txtproPrice.setText(String.valueOf(price));
            txtProTotal.setText(String.valueOf(total));
            btnAddCart.setEnabled(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_table1MouseClicked

    private void spinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinStateChanged
        int quantity = (Integer) spin.getValue();
        int total = 0;
        if (quantity <= 1) {
            spin.setValue(1);
            quantity = 1;
        }
        total = price * quantity;
        txtProTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_spinStateChanged

    private void btnAddCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCartActionPerformed

        DefaultTableModel tdf1 = (DefaultTableModel) table2.getModel();
        String name = txtproName.getText();
        String price1 = txtproPrice.getText();
        String total = txtProTotal.getText();
        int quantity = (Integer) spin.getValue();
        String Probill[] = {name, price1, String.valueOf(quantity), total};
        tdf1.addRow(Probill);
        grandtotal = grandtotal + Integer.parseInt(total);
        grandTotal.setText(String.valueOf(grandtotal));
        clear();
        jTextField4.setText("");
    }//GEN-LAST:event_btnAddCartActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cusNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusNameKeyReleased
        ValidateFields();        // TODO add your handling code here:
    }//GEN-LAST:event_cusNameKeyReleased

    private void cusMobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusMobileKeyReleased
        ValidateFields();        // TODO add your handling code here:
    }//GEN-LAST:event_cusMobileKeyReleased

    private void cusEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cusEmailKeyReleased
        ValidateFields();        // TODO add your handling code here:
    }//GEN-LAST:event_cusEmailKeyReleased

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this product?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            TableModel model = table2.getModel();
            String total = model.getValueAt(table2.getSelectedRow(), 3).toString();
            grandtotal = grandtotal - Integer.parseInt(total);
            grandTotal.setText(String.valueOf(grandtotal));
            DefaultTableModel tdf = (DefaultTableModel) table2.getModel();
            tdf.removeRow(table2.getSelectedRow());
        }
    }//GEN-LAST:event_table2MouseClicked

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        String custName = cusName.getText();
        String custMobile = cusMobile.getText();
        String custEmail = cusEmail.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String todayDate = sdf.format(date);
        String total = String.valueOf(grandtotal);
        String createdBy = Usermail;
        String billId = Bill.getText();
        String q4 = "insert into bill values('" + billId + "','" + custName + "','" + custMobile + "','" + custEmail + "','" + todayDate + "','" + total + "','" + createdBy + "')";
        conn c = new conn();
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        try {
            c.s.executeUpdate(q4);
            String path = "E:\\";

            PdfWriter.getInstance(doc, new FileOutputStream(path+" "+ billId + ".pdf"));
            doc.open();
            Paragraph startLine = new Paragraph("****************************************************************************************************************");
            Paragraph cafeName = new Paragraph("                                                                Cafe Management System\n");
            doc.add(cafeName);
            doc.add(startLine);
            doc.add(startLine);
            Paragraph para3 = new Paragraph("\tBill ID: " + billId + "\nCustomer Name: " + custName + "\nCustomer Email: " + custEmail + "\nTotal Paid:" + grandtotal+"\nCreateBy: "+createdBy+"\nDate: "+todayDate);
            doc.add(para3);
            doc.add(startLine);
            PdfPTable tb1 = new PdfPTable(4);
            tb1.addCell("Name");
            tb1.addCell("Price");
            tb1.addCell("Quantity");
            tb1.addCell("Total");
            for (int i = 0; i < table2.getRowCount(); i++) {
                String n = table2.getValueAt(i, 0).toString();
                String d = table2.getValueAt(i, 1).toString();
                String r = table2.getValueAt(i, 2).toString();
                String q = table2.getValueAt(i, 3).toString();
                tb1.addCell(n);
                tb1.addCell(d);
                tb1.addCell(r);
                tb1.addCell(q);
            }
            doc.add(tb1);
            doc.add(startLine);
            doc.add(startLine);
            Paragraph para4 = new Paragraph("Thank You,Please Visit Again.");
            doc.add(para4);
            JOptionPane.showMessageDialog(null, "Bill Generated Successfully.");
            if((new File("E:\\"+billId+".pdf")).exists()){
                Process p=Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler E:\\"+billId+".pdf");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "File is not Exists!");
        }
        doc.close();
        
        this.setVisible(false);
        new Dashboard(Usermail).setVisible(true);
    }//GEN-LAST:event_btnBillActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        String category = (String) combo.getSelectedItem();
        String searc=jTextField4.getText();
        String q3 = "select * from productTable where category='" + category + "' and name like '%"+searc+"%'";
        String proName = null;
        conn c = new conn();
        DefaultTableModel tdf = (DefaultTableModel) table1.getModel();
        tdf.setRowCount(0);
        try {
            ResultSet rs2 = c.s.executeQuery(q3);
            while (rs2.next()) {

                proName = rs2.getString("name");
                String tb[] = {proName};
                tdf.addRow(tb);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTextField4KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bill;
    private javax.swing.JButton btnAddCart;
    private javax.swing.JButton btnBill;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField cusEmail;
    private javax.swing.JTextField cusMobile;
    private javax.swing.JTextField cusName;
    private javax.swing.JLabel grandTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JSpinner spin;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTextField txtProTotal;
    private javax.swing.JTextField txtproName;
    private javax.swing.JTextField txtproPrice;
    // End of variables declaration//GEN-END:variables
}
