/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe_management_system;

import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Azizul Hakim'PC
 */
public class View_Edit_DeleteProduct extends javax.swing.JFrame {

    String email;

    /**
     * Creates new form NewJFrame
     */
    public View_Edit_DeleteProduct(String eemail) {
        email = eemail;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        updatebtn.setEnabled(false);
        deletebtn.setEnabled(false);
    }

    public void validateField() {
        String id = idl.getText();
        String name = txtname.getText();
        String category = (String) combocate.getSelectedItem();
        String price = txtprice.getText();
        if (!name.equals("") && !price.equals("")) {
            updatebtn.setEnabled(true);
            deletebtn.setEnabled(true);
        } else {
            updatebtn.setEnabled(false);
            deletebtn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        idl = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        combocate = new javax.swing.JComboBox<>();
        txtprice = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deletebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 313, -1, -1));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Price"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 519, 457));

        idl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idl.setForeground(new java.awt.Color(255, 255, 255));
        idl.setText("00");
        getContentPane().add(idl, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 201, 333, -1));

        txtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 234, 333, -1));

        combocate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combocate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combocateMouseClicked(evt);
            }
        });
        combocate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocateActionPerformed(evt);
            }
        });
        getContentPane().add(combocate, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 273, 333, -1));

        txtprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpriceKeyReleased(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 312, 333, -1));

        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                updatebtnComponentShown(evt);
            }
        });
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 351, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        jLabel1.setText("View,Edit & Delete Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 351, -1, -1));

        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 351, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 199, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 235, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 274, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1319, 15, 31, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("*Click on row to Delete Category");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 600, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Dashboard(email).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        validateField();
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyReleased
        validateField();        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceKeyReleased

    private void combocateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combocateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_combocateMouseClicked

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        txtname.setText("");
        txtprice.setText("");
        idl.setText("00");
        updatebtn.setEnabled(false);
        deletebtn.setEnabled(false);
    }//GEN-LAST:event_clearbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        String id6 = null, name1 = null, price1 = null, ccategory = null;
        String id = idl.getText();
        String name = txtname.getText();
        String category = (String) combocate.getSelectedItem();
        String price = txtprice.getText();
        String q3 = "update productTable set name='" + name + "',category='" + category + "',price='" + price + "' where id='" + id + "'";
        conn c = new conn();
        try {
            c.s.executeUpdate(q3);
            JOptionPane.showMessageDialog(null, "Product Updated Successfully!");
            txtname.setText("");
            txtprice.setText("");
            idl.setText("00");
            updatebtn.setEnabled(false);
            deletebtn.setEnabled(false);
        } catch (Exception e) {
        }
        DefaultTableModel tdf1 = (DefaultTableModel) jTable1.getModel();
        tdf1.setValueAt(id, jTable1.getSelectedRow(), 0);
        tdf1.setValueAt(name, jTable1.getSelectedRow(), 1);
        tdf1.setValueAt(category, jTable1.getSelectedRow(), 2);
        tdf1.setValueAt(price, jTable1.getSelectedRow(), 3);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        String q3 = "select * from category";
        conn c = new conn();
        try {
            ResultSet rs2 = c.s.executeQuery(q3);
            while (rs2.next()) {
                
                String category = rs2.getString("name");
                combocate.addItem(category);
            }
        } catch (Exception e) {
        }
        String q2 = "select * from productTable";
        
        try {
            ResultSet rs1 = c.s.executeQuery(q2);
            while (rs1.next()) {
                String id = String.valueOf(rs1.getInt("id"));
                String name1 = rs1.getString("name");
                String category = rs1.getString("category");
                String price = rs1.getString("price");
                String tbdata1[] = {id, name1, category, price};
                DefaultTableModel tdf1 = (DefaultTableModel) jTable1.getModel();
                tdf1.addRow(tbdata1);
                //combocate.addItem(category);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        TableModel model = jTable1.getModel();
        String id = (String) model.getValueAt(jTable1.getSelectedRow(), 0);
        String name = model.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String category = model.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String price = model.getValueAt(jTable1.getSelectedRow(), 3).toString();
        idl.setText(id);
        txtname.setText(name);
        txtprice.setText(price);
        combocate.setSelectedItem(category);
        updatebtn.setEnabled(true);
        deletebtn.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown

    }//GEN-LAST:event_jTable1ComponentShown

    private void updatebtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_updatebtnComponentShown

    }//GEN-LAST:event_updatebtnComponentShown

    private void combocateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combocateActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed

        String id = idl.getText();
        String name = txtname.getText();
        String q3 = "delete from producttable where id='" + id + "' and name='" + name + "'";
        conn c = new conn();
        try {
            c.s.executeUpdate(q3);
            JOptionPane.showMessageDialog(null, "Product Deleted Successfully!");
            txtname.setText("");
            txtprice.setText("");
            idl.setText("00");
            updatebtn.setEnabled(false);
            deletebtn.setEnabled(false);
        } catch (Exception e) {
        }
       /* this.setVisible(false);
        new View_Edit_DeleteProduct(email).setVisible(true);*/
        DefaultTableModel tdf1 = (DefaultTableModel) jTable1.getModel();
        tdf1.removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_deletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Edit_DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Edit_DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Edit_DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Edit_DeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Edit_DeleteProduct("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JComboBox<String> combocate;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel idl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
